#!/bin/bash -ex

WEBROOT=/var/www/youphptube

service apache2 start

# modify php configuration for YouPHPTube requirements
PHPINI=/etc/php/7.0/apache2/php.ini
sed -i "s|^memory_limit.*|memory_limit = 512M|" $PHPINI
sed -i "s|^upload_max_filesize.*|upload_max_filesize = 1000M|" $PHPINI
sed -i "s|^post_max_size.*|post_max_size = 1000M|" $PHPINI
sed -i "s|^allow_url_fopen.*|allow_url_fopen = On|" $PHPINI
sed -i "s|^max_execution.*|max_execution_time = 21600|" $PHPINI

service apache2 stop

# directory creation
mkdir $WEBROOT

#clone repository into the web directories
git clone https://github.com/DanielnetoDotCom/YouPHPTube.git $WEBROOT

# directory creation for videos
mkdir $WEBROOT/videos

# enable youtube download
curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl && chmod a+rx /usr/local/bin/youtube-dl

#Modify Database Generation Script For MariaDB Compatibility
#https://github.com/DanielnetoDotCom/YouPHPTube/issues/171
sed -i "61s|255|191|" $WEBROOT/install/database.sql

#Move Config Files Into Place
mv /opt/youphptube/configuration.php $WEBROOT/videos/configuration.php

# ensure correct permissions set on web directories
chown -R www-data:www-data $WEBROOT

# setup nginx for live streaming
mkdir /opt/build
cd /opt/build
git clone git://github.com/arut/nginx-rtmp-module.git
mkdir /HLS 
mkdir /HLS/live

touch /etc/apt/sources.list.d/backports.list
echo "deb http://ftp.debian.org/debian stretch-backports main" > /etc/apt/sources.list.d/backports.list
apt-get -y update
apt-get -y -t stretch-backports install libnginx-mod-rtmp

#Enable RTMP stats
mv /opt/build/nginx-rtmp-module/stat.xsl /var/www/html

#Enable SSL Chat
cat > /etc/apache2/mods-available/proxy.conf << EOF
<IfModule mod_proxy.c>
        ProxyPass /wss/ ws://127.0.0.1:8888/
</IfModule>
EOF

#Copy nginx conf into place
mv /opt/nginx/nginx.conf /etc/nginx/nginx.conf

#Start MySQL
service mysql start

##---------------YouPHPTube-----------------##
#Execute YouPHPTube Create Database and Run Database Structure Script
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_BATCHDB="mysql --user=root --password=$MYSQL_PASS --database=yphptube --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

#Create Database
$MYSQL_ADMIN create yphptube; 

# Populate database
$MYSQL_BATCHDB < $WEBROOT/install/database.sql
$MYSQL_BATCHDB < /opt/populatedb/usersyphptube.sql
$MYSQL_BATCHDB < /opt/populatedb/configurationsyphptube.sql
$MYSQL_BATCHDB < /opt/populatedb/categoriesyphptube.sql

#tubepass is changed at firstboot non-interactively (Secure At First Boot)
$MYSQL_BATCH -e "grant all on yphptube.* to 'tubeuser'@localhost identified by 'tubepass';"

#Enable Apache Mods 
a2enmod proxy_wstunnel
a2enmod rewrite

#Enable/Disable Sites
a2dissite 000-default
a2ensite youphptube

# stop mysql server
/etc/init.d/mysql stop

# Purge Temp Files
rm -rf /opt/build
rm -rf /opt/populatedb
rm -rf /opt/youphptube
rm -rf /opt/nginx

# Remove Enabled nginx sites
rm /etc/nginx/sites-enabled/default
