#!/bin/bash -ex

WEBROOT=/var/www/youphptube

service apache2 start

# modify php configuration for YouPHPTube requirements
PHPINI=/etc/php/7.0/apache2/php.ini
sed -i "s|^memory_limit.*|memory_limit = 512M|" $PHPINI
sed -i "s|^upload_max_filesize.*|upload_max_filesize = 1000M|" $PHPINI
sed -i "s|^post_max_size.*|post_max_size = 1000M|" $PHPINI
sed -i "s|^allow_url_fopen.*|allow_url_fopen = On|" $PHPINI
sed -i "s|^max_execution.*|max_execution_time = 21600|" $PHPINI

service apache2 stop

# directory creation
mkdir $WEBROOT

#clone repository into the web directories
git clone https://github.com/DanielnetoDotCom/YouPHPTube.git $WEBROOT

# directory creation for videos
mkdir $WEBROOT/videos

# enable youtube download
curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl && chmod a+rx /usr/local/bin/youtube-dl

#Modify Database Generation Script For MariaDB Compatibility
sed -i "61s|255|191|" $WEBROOT/install/database.sql

#Move Config Files Into Place
mv /opt/youphptube/configuration.php $WEBROOT/videos/configuration.php

# ensure correct permissions set on web directories
chown -R www-data:www-data $WEBROOT

# setup nginx for live streaming
mkdir /opt/build
cd /opt/build
git clone git://github.com/arut/nginx-rtmp-module.git
wget http://nginx.org/download/nginx-1.14.0.tar.gz
tar xzf nginx-1.14.0.tar.gz
cd nginx-1.14.0
./configure --with-http_ssl_module --with-http_stub_status_module --add-module=../nginx-rtmp-module 
make
make install
mkdir /usr/local/nginx/ssl/
mkdir /HLS 
mkdir /HLS/live
cp /opt/build/nginx-rtmp-module/stat.xsl /usr/local/nginx/html
mv /usr/local/nginx/conf/nginx.conf /usr/local/nginx/conf/nginx.conf.old
cd /usr/local/nginx/conf/
wget https://raw.githubusercontent.com/DanielnetoDotCom/YouPHPTube/master/plugin/Live/install/nginx.conf

#Edit Nginx Config To Listen on 444
sed -i "/listen 8080/ a \\\t            listen 444 ssl\;" /usr/local/nginx/conf/nginx.conf
sed -i "/listen 444/ a \\\t            ssl_certificate \/etc\/ssl\/certs\/ssl-cert-snakeoil\.pem;" /usr/local/nginx/conf/nginx.conf
sed -i "/listen 444/ a \\\t            ssl_certificate_key \/etc\/ssl\/private\/ssl-cert-snakeoil.key\;" /usr/local/nginx/conf/nginx.conf
sed -i "/listen 444/ a \\\t            ssl_certificate_key \/etc\/ssl\/private\/ssl-cert-snakeoil.key\;" /usr/local/nginx/conf/nginx.conf

#Enable SSL Chat
cat > /etc/apache2/mods-available/proxy.conf << EOF
<IfModule mod_proxy.c>
        ProxyPass /wss/ ws://127.0.0.1:8888/
</IfModule>
EOF

#Start MySQL
service mysql start

##---------------YouPHPTube-----------------##
#Execute YouPHPTube Create Database and Run Database Structure Script
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_BATCHDB="mysql --user=root --password=$MYSQL_PASS --database=yphptube --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

#Create Database
$MYSQL_ADMIN create yphptube; 

# Populate database
$MYSQL_BATCHDB < $WEBROOT/install/database.sql
$MYSQL_BATCHDB < /opt/populatedb/usersyphptube.sql
$MYSQL_BATCHDB < /opt/populatedb/configurationsyphptube.sql
$MYSQL_BATCHDB < /opt/populatedb/categoriesyphptube.sql

#tubepass is changed at firstboot non-interactively (Secure At First Boot)
$MYSQL_BATCH -e "grant all on yphptube.* to 'tubeuser'@localhost identified by 'tubepass';"

#Enable Apache Mods 
a2enmod proxy_wstunnel
a2enmod rewrite

#Enable/Disable Sites
a2dissite 000-default
a2ensite youphptube

# stop mysql server
/etc/init.d/mysql stop

rm -rf /opt/build
rm -rf /opt/populatedb
rm -rf /opt/youphptube
