#!/bin/bash -ex

WEBROOT=/var/www/youphptube
SRC=/usr/local/src

# modify php configuration for YouPHPTube requirements
PHPINI=/etc/php/7.0/apache2/php.ini
sed -i "s|^memory_limit.*|memory_limit = 512M|" $PHPINI
sed -i "s|^upload_max_filesize.*|upload_max_filesize = 1000M|" $PHPINI
sed -i "s|^post_max_size.*|post_max_size = 1000M|" $PHPINI
sed -i "s|^allow_url_fopen.*|allow_url_fopen = On|" $PHPINI
sed -i "s|^max_execution.*|max_execution_time = 21600|" $PHPINI

# Apache - enable SSL Chat
cat > /etc/apache2/mods-available/proxy.conf << EOF
<IfModule mod_proxy.c>
        ProxyPass /wss/ ws://127.0.0.1:8888/
</IfModule>
EOF

# more Apache conf
a2dissite 000-default
a2ensite youphptube
a2enmod proxy_wstunnel
a2enmod rewrite

# clone repo and create required dirs
git clone https://github.com/DanielnetoDotCom/YouPHPTube.git $WEBROOT
mkdir $WEBROOT/videos

# Move Config File Into Place
mv $SRC/youphptube_configuration.php $WEBROOT/videos/configuration.php

# ensure correct permissions set on web directories
chown -R www-data:www-data $WEBROOT

# enable remote video download
curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
chmod a+rx /usr/local/bin/youtube-dl

# install nginx rtmp module (and nginx itself) from backports & configure
# including stats
echo "deb http://deb.debian.org/debian stretch-backports main" > /etc/apt/sources.list.d/backports.list
apt-get -y update
apt-get -y -t stretch-backports install libnginx-mod-rtmp
mv $SRC/nginx.conf /etc/nginx/nginx.conf
rm /etc/nginx/sites-enabled/default
URL=https://raw.githubusercontent.com/arut/nginx-rtmp-module/master
wget $URL/stat.xsl -O /var/www/html/stat.xsl

##---------------YouPHPTube-----------------##

service mysql start

# Execute YouPHPTube Create Database and Run Database Structure Script
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_BATCHDB="mysql --user=root --password=$MYSQL_PASS --database=yphptube --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

#Create Database
$MYSQL_ADMIN create yphptube; 

# Modify Database Generation Script For MariaDB Compatibility
# https://github.com/DanielnetoDotCom/YouPHPTube/issues/171
sed -i "61s|255|191|" $WEBROOT/install/database.sql

# Populate database
$MYSQL_BATCHDB < $WEBROOT/install/database.sql
$MYSQL_BATCHDB < $SRC/populatedb/usersyphptube.sql
$MYSQL_BATCHDB < $SRC/populatedb/configurationsyphptube.sql
$MYSQL_BATCHDB < $SRC/populatedb/categoriesyphptube.sql

# tubepass is changed at firstboot non-interactively (Secure At First Boot)
$MYSQL_BATCH -e "grant all on yphptube.* to 'tubeuser'@localhost identified by 'tubepass';"

service mysql stop

# Purge Temp Files
rm -rf $SRC/populatedb
