#!/bin/bash -e
# regenerate YouPHPTube secrets and tubeuser mysql password

. /etc/default/inithooks

CONF=/var/www/youphptube/videos/configuration.php
CONF2=/var/www/YouPHPTube-Encoder/videos/configuration.php

gen_random() {
    date +%s | sha256sum | base64 | head -c 13
}

SALT=$(gen_random)
CHANNEL=$(gen_random)

sed -i "\|\$global.*salt|s|=.*|= '$SALT';|" $CONF

mysql -u root -e "UPDATE yphptube.users SET channelName = '$CHANNEL' WHERE id = '1';"

USER=tubeuser
PASSWORD=$(mcookie)

sed -i "\|\$mysqlPass|s|=.*|= '$PASSWORD';|" $CONF
sed -i "\|\$mysqlPass|s|=.*|= '$PASSWORD';|" $CONF2

$INITHOOKS_PATH/bin/mysqlconf.py --user="$USER" --pass="$PASSWORD"
