#!/bin/bash -e
# regenerate YouPHPTube secrets and tubeuser mysql password

. /etc/default/inithooks

CONF=/var/www/youphptube/videos/configuration.php
CONF2=/var/www/YouPHPTube-Encoder/videos/configuration.php

gen_random() {
    chars_req=$1
    unset rand
    while [[ ${#rand} -lt $chars_req ]]; do
        chars=$(dd bs=25 count=1 if=/dev/urandom 2>/dev/null | tr -dc 'a-z0-9')
        rand="${rand}${chars}"
    done
    echo "${rand:0:$chars_req}"
}

SALT=$(gen_random 13)
CHANNEL=$(gen_random 13)

sed -i "\|\$global.*salt|s|=.*|= '$SALT';|" $CONF

mysql -u root -e "UPDATE yphptube.users SET channelName = '$CHANNEL' WHERE id = '1';"

USER=tubeuser
PASSWORD=$(mcookie)

sed -i "\|\$mysqlPass|s|=.*|= '$PASSWORD';|" $CONF
sed -i "\|\$mysqlPass|s|=.*|= '$PASSWORD';|" $CONF2

$INITHOOKS_PATH/bin/mysqlconf.py --user="$USER" --pass="$PASSWORD"
