#!/bin/bash -e
# regenerate YouPHPTube secrets and tubeuser mysql password

. /etc/default/inithooks

CONF=/var/www/youphptube/videos/configuration.php

gen_random() {
    cat /dev/urandom | tr -dc 'a-z0-9' | fold -w 13 | head -n 1
}

SALT=$(gen_random)
CHANNEL=$(gen_random)

sed -i "\|\$global.*salt|s|=.*|= '$SALT';|" $CONF

mysql -u root -e "UPDATE yphptube.users SET channelName = '$CHANNEL' WHERE id = '1';"

USER=tubeuser
PASSWORD=$(mcookie)

sed -i "\|\$mysqlPass|s|=.*|= '$PASSWORD';|" $CONF

$INITHOOKS_PATH/bin/mysqlconf.py --user="$USER" --pass="$PASSWORD"
