#!/bin/bash -e
# set youphptube admin password and email

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
$INITHOOKS_PATH/bin/youphptube.py --pass="$APP_PASS" --email="$APP_EMAIL"